project:
  type: website
  output-dir: _site
  # execute-dir: project

execute:
  freeze: auto

website:
  title: "Amin G. Alhashim"
  site-url: "https://hashcx.github.io/TidyTuesday"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        href: https://github.com/hashcx/TidyTuesday
      - icon: rss
        href: index.xml

format:
  html:
    theme:
      light: [zephyr, styles/custom.scss]
      dark: [darkly, styles/custom.scss]
    toc: true
    code-fold: true
    link-external-newwindow: true
